version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ForecastSteps"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-iq67aiu1indy"
s3_prefix = "ForecastSteps"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Email=\"lopez470@umn.edu\" BucketName=\"forecastblogluseloso\" ParameterFile=\"params_test.json\""

