version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ForecastSteps"
s3_prefix = "ForecastSteps"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"